export const weatherImageMapping = {
  "clear sky": "clear-sky",
  "few clouds": "few-clouds",
  "scattered clouds": "scattered-clouds",
  "broken clouds": "broken-clouds",
  "overcast clouds": "overcast-clouds",
  //   rain
  "light rain": "rain",
  "moderate rain": "rain",
  "heavy intensity rain": "rain",
  "very heavy rain": "rain",
  "extreme rain": "rain",
  "freezing rain": "rain",
  "light intensity shower rain": "rain",
  "shower rain": "rain",
  "heavy intensity shower rain": "rain",
  "ragged shower rain": "rain",
  //   light rain
  "light intensity drizzle": "light-rain",
  drizzle: "light-rain",
  "heavy intensity drizzle": "light-rain",
  "light intensity drizzle rain": "light-rain",
  "drizzle rain": "light-rain",
  "heavy intensity drizzle rain": "light-rain",
  "shower rain and drizzle": "light-rain",
  "heavy shower rain and drizzle": "light-rain",
  "shower drizzle": "light-rain",
  //   snow
  "light snow": "snow",
  snow: "snow",
  "heavy snow": "snow",
  "light shower sleet": "snow",
  "shower sleet": "snow",
  "light rain and snow": "snow",
  "rain and snow": "snow",
  "light shower snow": "snow",
  "shower snow": "snow",
  "heavy shower snow": "snow",
  //   thunderstorm
  thunderstorm: "thunderstorm",
  "thunderstorm with light rain": "thunderstorm",
  "thunderstorm with rain": "thunderstorm",
  "thunderstorm with heavy rain": "thunderstorm",
  "light thunderstorm": "thunderstorm",
  "heavy thunderstorm": "thunderstorm",
  "ragged thunderstorm": "thunderstorm",
  "thunderstorm with light drizzle": "thunderstorm",
  "thunderstorm with drizzle": "thunderstorm",
  "thunderstorm with heavy drizzle": "thunderstorm",
  //   mist
  mist: "mist",
  smoke: "mist",
  haze: "mist",
  "sand/dust whirls": "mist",
  fog: "mist",
  sand: "mist",
  dust: "mist",
  "volcanic ash": "mist",
  squalls: "mist",
  tornado: "mist",
};
